# render.yaml
services:
  - type: web
    name: Final-MP3-download
    env: python
    # 关键修改：将 pip3 更改为 pip
    buildCommand: "pip install -r requirements.txt" 
    startCommand: "gunicorn app:app"
    systemPackages:
      - ffmpeg