services:
  - type: web
    name: last-mp3-download
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    systemPackages:
      - ffmpeg
      - nodejs  # <--- 新增这行：安装 Node.js 以支持 yt-dlp 解密